# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b19d075207593fc8acd6c35720a1c56e52b987f32e02d962810b306b4e0c2f8bab573965d1c35140df6e5614e2804fbdc6c030ee5c10bf1584d1602d407f2e8

test:
  secret_key_base: 30e3b287673b6470865cc62dd61b0d97758b4c4ab01314481ad4c8f91671b4e69bbebd833ad708f623f14894ef2c9bc56cd131be8693f77cf550dce0f0ccb317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
